configfile: "config/config.yaml"

SCRATCH = config['scratch']
RESULTS = config['resulstdir']
MAC = config['mac']
CHROMS = list(range(21, 23))


rule all:
    input:
        f'{RESULTS}/predictions_bed'


include: "rules/prepare_data.smk"
include: "rules/local_ancestry.smk"
